- menu_name: "Services"

- name: "Aménagement"
  url: "/amenagement.htm"
  title: "Conception de votre aménagement et réalisation de votre Jardin"

- name: "Entretien"
  url: "/entretien.htm"
  title: "Entretien complet de votre jardin"

- name: "Plantes"
  url: "/plantes.htm"
  title: "Vente, installation et entretien de plantes vertes"
  
- name: "Terrasses"
  url: "/terrasse.htm"
  title: "Aménagement de terrasses et autres menuiseries"

- name: "Elagage"
  url: "/elagage.htm"
  title: "Élagage de vos arbres"
  
- name: "Contact"
  url: "/contact.htm"
  title: "Contact"
