- menu_name: "Services"

- name: "Aménagement"
  url: "/amenagement.htm"
  title: "Subscribe to RSS Feed"

- name: "Entretien"
  url: "/entretien.htm"
  title: "Subscribe to Atom Feed"

- name: "Plantes"
  url: "/plantes.htm"
  title: "Sitemap for Google Webmaster Tools"
  
- name: "Terrasses"
  url: "/terrasse.htm"
  title: "Contact"

- name: "Elagage"
  url: "/contact/"
  title: "Contact"
  
- name: "Contact"
  url: "/elagage.htm"
  title: "Contact"
